a.out:main.o student.o savefile.o
        cc -g main.o student.o savefile.o
main.o:main.c
        cc -c main.c
student.o:student.c
        cc -c student.c
savefile.o:savefile.c
        cc -c savefile.c